### PR TITLE
Logo folders added

### PR DESCRIPTION
**Pull request by ArsalanShah124**

### CODE REVIEW

**Comment by amchagas** [comment]
Hi! 
thanks for submitting this pull request! the logos look very nice and I think they will take care of issue #29  quite nicely. 
One comment is that on folder2, the main logo read "be free and open source hardware" could this be updated to "build free and open science hardware" as the other designs in folder 1?

thanks!

**Comment by ArsalanShah124** [comment]
Hi, 

Do you mean the foshdocument? 

Thanks

**Comment by amchagas** [comment]
Here some examples:
[example1](https://github.com/FOSH-following-demand/FOSH-following-demand.github.io/blob/8e27bef9393acdfa7c34d620aefe4da4e26ab5ef/bfoshlogo1/bfoshfacebookpost1.png)
[example2](https://github.com/FOSH-following-demand/FOSH-following-demand.github.io/blob/8e27bef9393acdfa7c34d620aefe4da4e26ab5ef/bfoshlogo2/foshlogodocument.png)

**Comment by ArsalanShah124** [comment]
Yup, exactly the document. I will change and I will suggest you remove that from GitHub as well and keep the document only to your team and yourself. 

I will make the changes and send it over.

Thanks

**Comment by amchagas** [comment]
thanks!

**Pull request merged**
