### PR TITLE
2018-11-17 gooshie's Changelog of FOSH-following-demand

### PR DESCRIPTION
**Pull request by gooshie**
​
# Menu & Language Active Page Indication

### These Changes can be viewed at:  http://gooshie.me/amchagas/

- #### Minor changes to _config.yml (Remember to adjust url & baseurl settings after merge.)

- #### Added => /assets/css/style.css to color active page Menu & Language

- #### Changed => /_includes/menu.html
   - This affects the main menu UI
   - Added class=active to anchor tag of active page
   - Changed permalink front matter (removed trailing "/") on several pages to match _config.yml settings so that matching can be used to determine active page.
   - Active page in menu indicated by color change.
-  #### Changed => /_includes/selector.html
   - This affects Language menu UI
   - Added a case statement to replace language abbreviation with complete word.
   - Added class=active to anchor tag of active page
   - There is a fall through for when new languages are added so they display as abbreviation until they are added to the case statement.
   - Active language indicated by color change.

### CODE REVIEW

**Comment by gooshie** [comment]
### Hi Andre,
### Could you please "squash" those commits before merging?

**Comment by amchagas** [comment]
Hey,

I'm trying to, but seems I can't figure this last conflict out. I can check this again later today.

**Comment by gooshie** [comment]
I removed a "#" from the description.

**Comment by gooshie** [comment]
My mistake. I forgot to merge yours back to mine before I made changes. I'm still new to merging. Thanks for your patience.

**Comment by gooshie** [comment]
Everything got pulled in. I think the issue really was that I should have rebased before I did the PR. I'm gonna close the this PR.

**Comment by amchagas** [comment]
Hey, Just wanted to check in and make sure things are up to date since I was looking at this network plot and got confused https://github.com/FOSH-following-demand/FOSH-following-demand.github.io/network 
:stuck_out_tongue_winking_eye:

**Comment by gooshie** [comment]
Andre, That graph shows my fork of the project and that mine ends on the
17th because I've not done anything since then. The FOSH on top is the
actual site and shows your fork and merge and more recent activity. I hope
my explanation is understandable and helpful.  -gooshie-

**Comment by gooshie** [comment]
The reason it is "tracking" my activity on my gh-pages fork of the project is because I have had pull request merged into the project and/or because I am a member of the project. When I am ready and have time to make another contribution I will merge the project back to my gh-pages BEFORE I make changes and that should prevent merge conflicts. I think if I'd had REBASED it would have fixed the conflict that occurred in this PR. 🤕  I'm still learning things about git procedures. I need to start making a habit of using branches locally even on my own projects and stop working on the master branch all the time. I'll give you this 🥇  for being patient with this PR conflict, or would you prefer? => 🍦

**Comment by amchagas** [comment]
That was already clear, what I'm confused about is whether or not all the changes you have that are running in parallel are the same or different ones from the ones we squashed a couple of days ago...
Sorry, to be bothering with this, it is just that sometimes I end up overwriting good code with bad/outdated code due to my bad habits on git...

**Comment by amchagas** [comment]
lol, ok, I see we are both aware that we need to improve git working habits...

**Comment by gooshie** [comment]
Yes, what we should both do when we are going to edit the project is to create a "working" branch. I must do one other thing BEFORE I create my working branch and that is to sync my master with your master first. Okay, so now that we have a working branch, we do our edits there, if we don't like the changes we can simply kill the branch and create a new working branch OR create a 2nd working branch to try another set of edits. When we feel good about a branch we can then squash it down to one commit before merging it to master. In my case if I do this correctly there will ONLY be a conflict when we happen to both be making changes at the same time. Then a REBASE may resolve that type conflict easier if the conflicts are ONLY time related. I hope my explanation is understandable.

**Pull request closed without merging**
