### PR TITLE
Spanish version of webpage

### PR DESCRIPTION
**Pull request by pgpadilla**
My support for this project. Please, let me know when it's available online so I can share to the Latin American community. Thank you! Great project!

Pierre

### CODE REVIEW

**Comment by amchagas** [comment]
Thanks Pierre! I'll review the PR and update everything as soon as possible

**Comment by amchagas** [comment]
Hi Pierre, 

upon a closer look I see that you forked this repository a while back. It seems that the version you were working on is some commits behind the base repository. 

To avoid writing over the newest commits on this repo, could you please update your branch before we merge your changes?  I would suggest making an extra copy of the translation files you created, just to be on the safe side (the folder structure of the repository also changed a bit). If you are unsure how to update your branch, let me know, I can help out!

Thanks for the translation and sorry for this bit of extra work!

**Comment by pgpadilla** [comment]
Hey Andre. Don't worry, I'll update the repo and add the last translation. I should have done that before but I wasn't sure.

**Comment by amchagas** [comment]
Closing this PR as we implemented the spanish translation on #38

**Pull request closed without merging**
